In [5]:
import numpy as np

# 10.1 loadtxt & savetxt 
# (Text type의 데이터를 읽고 저장하는 기능)

In [6]:
import os
os.getcwd()

'D:\\dudwlsrla92\\Python\\python_jupyter\\2. Numpy'

In [7]:
a = np.loadtxt('TEST.txt')
print(a)

[1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9]


In [8]:
a[:10]

array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9])

In [9]:
a_int = a.astype(int)

In [10]:
a_int[:3]

array([1, 2, 3])

In [11]:
np.savetxt('numpy_save_test.csv', a_int, delimiter=',')  # csv 파일로 저장

# 10.2 numpy object – npy

- Numpy object(pickle) 형태로 데이터를 저장하고 불러옴
- Binary 파일 형태
      - np.save('npy_test', arr=a_int)
      - npy_array = np.load(file='npy_test.npy')