In [2]:
import numpy as np

# #1. Vector(1차원) - (4,)

In [3]:
a = np.array([1,4,5,8],float)

print(a)

[1. 4. 5. 8.]


# #2. Matrix(2차원) - (4,3)

In [4]:
Matrix = [1,2,3,4],[5,6,7,8],[9,10,11,12]

print(Matrix)
print(np.array(Matrix,int).shape)
np.array(Matrix,int)

([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12])
(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# #3. Tensor(3차원) - (4,3,4)

In [5]:
tensor = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
          [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
          [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
          [[1,2,3,4],[5,6,7,8],[9,10,11,12]]]

print(tensor)
print(np.array(tensor,int).shape)
np.array(tensor,int)

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]
(4, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

# #4. ndim & size
- ndim 차원의 수
- size 데이터의 수

In [9]:
print(np.array(tensor,int).ndim)
print(np.array(tensor,int).size)

3
48


1

# #5. dtype
- single element가 가지는 데이터 타입
- C의 데이터 타입과 호환
- nbytes - ndarray object의 메모리 크기를 바이트 단위로 변환함

  
- 기본 default는 64로 되어있으며,
- 64 - 1개당 8bite
- 32 - 1개당 4bite

In [12]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.float32)       ) # 32bite single type // '5' str 문자열
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.float64).nbytes) # 24 = 데이터가 6개니까 한개당 4bite

[[1.  2.  3. ]
 [4.5 5.  6. ]]
48


# #6. reshape
- shape의 (3,4)는 행 3 열 4개인 매트릭스를 뜻한다.
- reshape(3,4)는 3행 4열의 매트릭스를 만들어준다.
- array의 shape을 변경함(element의 개수는 동일)

- -1: size를 기반으로 row 개수 선정된다. n과같음
-  -1은 알아서 맞춰달라는 명령어(size를 기반으로 row 개수 선정)

In [14]:
matrix = [[1,2,3,4],[5,6,7,8]]
print(np.array(matrix).shape)
print(np.array(matrix).reshape(8,).shape)
print(np.array(matrix).reshape(2,1,4))
print(np.array(matrix).reshape(-1,2).shape) 

(2, 4)
(8,)
[[[1 2 3 4]]

 [[5 6 7 8]]]
(4, 2)


# #7. flatten
- 다차원 array를 1차원 array로 변환

In [18]:
test_matrix = [[[1,2,3,4], [5,6,7,8]], [[2,3,4,5], [6,7,8,9]]]
print(np.array(test_matrix))
np.array(test_matrix).flatten()

[[[1 2 3 4]
  [5 6 7 8]]

 [[2 3 4 5]
  [6 7 8 9]]]


array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 9])