### 7.2 Dot product (Matrix 곱셈)
- (l,m) x (m,n) -> (l,n)

In [153]:
test_a = np.arange(1,7).reshape(2,3)
print(test_a)
test_b = np.arange(7,13).reshape(3,2)
print(test_b)
test_a.dot(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

### 7.3 Transpose

In [159]:
test_a = np.arange(1,7).reshape(2,3)
test_a.transpose()
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 7.4 Broadcasting (Shape이 다른 배열간 연산 지원)
- test_matrix + scalar
- test_matrix – scalar
- test_matrix * scalar
- test_matrix / scalar # 나누기
- test_matrix // scalar # 몫
- test_matrix ** 2 # 제곱


In [160]:
test_matrix = np.array([[1,2,3], [4,5,6]], float)
scalar = 3
test_matrix + scalar # Matrix – Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [169]:
# Matrix와 Vector간의 연산도 가능
test_matrix = np.arange(1,13).reshape(4,3)
print(test_matrix)

test_vector = np.arange(10,40,10)
print(test_vector)

print(test_matrix + test_vector)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]
