# 8.1 All & Any 

In [4]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
np.any(a>5)  # True # any – 하나라도 조건에 만족하면 True
np.any(a<0)  # False
np.all(a>5)  # False # all – 모두가 조건을 만족해야 True
np.all(a<10) # True

a > 5 # array([False, False, False, False, False, False, True, True, True, True],dtype=bool)


array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b   # 배열의 크기가 동일할 때 원소간 비교 가능
test_a == test_b

array([False, False, False])

In [11]:
test_a == test_b
(test_a > test_b).any()

True

# 8.2 Logical Operation

In [13]:
a = np.array([1, 3, 0], float)
b = np.logical_and(a>0, a<3)  # 0<a<3이 안되기 때문에 and 조건을 써야한다. 
print(b)

[ True False False]


In [15]:
c = np.logical_not(b)
print(c)

[False  True  True]


In [16]:
np.logical_or(b,c)

array([ True,  True,  True])

In [19]:
d = np.where(a>0, 3, 2) # where(condition(조건), True면 3으로, False면 2로 채워라)
print(d)

[3 3 3 3 3 3 3 3 3 3]


In [23]:
a = np.arange(10, 20)
print(a)
np.where(a>15) # index 값 반환

[10 11 12 13 14 15 16 17 18 19]


(array([6, 7, 8, 9], dtype=int64),)

In [26]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)
np.isnan(a) # is Not a Number?
np.isfinite(a) # is finite number?

[ 1. nan inf]


array([False,  True, False])

# 8.3 argmax & argmin 
# (array내 최대값 또는 최소값의 index를 리턴)

In [27]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [33]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
print(a)

[[ 1  2  4  7]
 [ 9 88  6 45]
 [ 8 78 23  3]]


array([1, 1, 2, 1], dtype=int64)

In [34]:
np.argmax(a, axis=1)  # 인덱스 자릿수

array([3, 1, 1], dtype=int64)

In [35]:
np.argmax(a, axis=0)  # 수치를 그대로 표현하지 않음

array([1, 1, 2, 1], dtype=int64)

In [36]:
np.argmin(a, axis=1)

array([0, 2, 3], dtype=int64)

In [37]:
np.argmin(a, axis=0)

array([0, 0, 0, 2], dtype=int64)