In [15]:
import numpy as np

# 3. Array Shape

### 3.1 Vector(1차원)

In [24]:
test_array = np.array([1,4,5,8],float)
print(test_array)
# shape는 (4,) : 1차원에 4개의 element가 있는 벡터

[1. 4. 5. 8.]


### 3.2 Matrix(2차원)

In [30]:
matrix = [[1,2,5,8],[2,3,4,9],[4,5,6,7]]
np.array(matrix,int).shape

# shape은 (3,4) : 행이 3개, 열이 4개인 매트릭스

(3, 4)

### 3.3 Tensor(3차원) 

In [34]:
tensor = [[[1,2,5,8],[2,3,4,9],[4,5,6,7]],
          [[1,2,5,8],[2,3,4,9],[4,5,6,7]],
          [[1,2,5,8],[2,3,4,9],[4,5,6,7]],
          [[1,2,5,8],[2,3,4,9],[4,5,6,7]]]
np.array(tensor,int).shape

# shape은 (4,3,4) : 평면이 4개 형이 3개 열이 4개인 텐서

(4, 3, 4)

### 3.4 ndim & size 

In [38]:
print(np.array(tensor, int).ndim) # 차원이 몇차원이냐
print(np.array(tensor, int).size) # 데이터의 개수

3
48


### 3.5 dtype

In [43]:
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.float32)       ) # 32bite single type // '5' str 문자열
print(np.array([[1,2,3],[4.5,'5','6']],dtype=np.float32).nbytes) # 24 = 데이터가 6개니까 한개당 4bite

[[1.  2.  3. ]
 [4.5 5.  6. ]]
24


- Single element가 가지는 데이터 타입
- C의 데이터 타입과 호환
- nbytes - ndarray object의 메모리 크기를 바이트 단위로 반환함.

### 3.6 reshape

In [46]:
test_matrix= [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [47]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

- Array의 shape을 변경함 (element의 개수는 동일)
- Array의 size만 같다면 다차원으로 자유뢰 변형 가능

In [52]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [48]:
# -1은 알아서 맞춰달라는 명령어(size를 기반으로 row 개수 선정)

In [51]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

### 3.7 flatten

In [58]:
test_matrix = [[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[6,7,8,9]]]
np.array(test_matrix).flatten().shape

(16,)

# 4. Indexing and Slicing

### 4.1 Indexing

In [62]:
# list[][] -> [  , ] 이렇게 표현할 수 있다.
a = np.array([[1,2,3],[4,5,6]],int)
print(a)
print(a[0, 0]) # 2차원 배열 표기법 1
print(a[0][0]) # 2차원 배열 표기법 2

[[1 2 3]
 [4 5 6]]
1
1


- list와 달리 이차원 배열에서 [0,0]과 같은 표기법을 제공함
- matrix일 경우 앞은 행(row) 뒤는 열(col)을 의미한다.

### 4.2 slicing

In [66]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int) 
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [68]:
print(a[:,2:])
print(a[1,1:3]) 
print(a[1:3])     # 행이 먼저 표시되며 없는 곳은 자동제외로 print된다
print(a[:,::2])

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]
[[ 1  3  5]
 [ 6  8 10]]


- list와 달리 행과 열 부분을 나눠서 slicing이 가능함
- matrix의 부분 집합을 추출할 때 유용함

# 5. Creation Function

### 5.1 arange

In [74]:
print(np.arange(10))                 # arange - List의 range와 같은 효과
print(np.arange(0, 5, 0.5))          # floating point도 표시 가능
print(np.arange(0, 5, 0.5).tolist()) # list로 만들어준다
print(np.arange(30).reshape(5, 6))   # size가 같으면 가능

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 5.2 ones, zeros and empty

In [78]:
np.zeros(shape=(10,), dtype=np.int8) # 원소가 10개인 벡터 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [81]:
np.zeros(shape=(10,),dtype=np.int8).nbytes

10

In [83]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
np.ones((2,5)).nbytes

80

In [87]:
np.empty((3,5))

array([[2.12199579e-314, 6.36598737e-314, 1.06099790e-313,
        1.48539705e-313, 1.90979621e-313],
       [2.33419537e-313, 2.75859453e-313, 3.18299369e-313,
        3.60739285e-313, 4.03179200e-313],
       [4.45619116e-313, 4.88059032e-313, 5.30498948e-313,
        5.72938864e-313, 6.15378780e-313]])

### 5.3 Something like
- 기존 ndarray의 shape 크기 만큼 1,0 또는 empty array를 반환

In [90]:
test_matrix = np.arange(30).reshape(5,6)
print(np.ones_like(test_matrix))
print(np.zeros_like(test_matrix))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### 5.4 identity (단위 행렬 생성)

In [93]:
np.identity(n=3,dtype=np.int8) # n = number of rows

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [95]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5.5 eye(대각선이 1인 행렬)

In [97]:
np.eye(N=3,M=5,dtype=np.int8) # 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [98]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
np.eye(3,5,k=2) # k = start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5.6 diag(대각 행렬의 값을 추출)

In [108]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix))
print(np.diag(matrix,k=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]


### 5.7 Random sampling(데이터 분포에 따른 sampling으로 array를 생성)

- np.random.uniform(최소,최대,개수)    # 균등 분포
- np.random.normal(평균,표준편차,개수) # 정규 분포
- np.random.binomial(n, p, size)       # 이항 분포
- np.random.poisson(lam. size)         # 포아송 분포
- np.random.standard_t(df, size)       # t-분포
- np.random.f(dfnum, dfden, size)      # F-분포 

In [111]:
np.random.seed(seed=1000)
print(np.random.uniform(0, 1, 10).reshape(2,5)) # 균등분포 (최소, 최대, 개수)
print(np.random.normal(0, 1, 10).reshape(2,5))  # 정규분포 (평균 표준편차 개수)

[[0.65358959 0.11500694 0.95028286 0.4821914  0.87247454]
 [0.21233268 0.04070962 0.39719446 0.2331322  0.84174072]]
[[ 0.66728131 -0.80611561 -1.19606983 -0.40596016 -0.18237734]
 [ 0.10319289 -0.13842199  0.70569237  1.27179528 -0.98674733]]


# 6. Operation Function

### 6.1 SUM

In [114]:
test_array = np.arange(1,11)
test_array.sum(dtype=np.float)

55.0

### 6.2 Axis (모든 operation function을 실행할 때, 기준이 되는 dimension축)

In [118]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [127]:
print(test_array.sum(axis=0)) # 행 (세로)
print(test_array.sum(axis=1)) # 열 (가로)

[15 18 21 24]
[10 26 42]


### 6.3 평균 및 표준편차

In [128]:
print(test_array.mean())
print(test_array.mean(axis=0))
print(test_array.mean(axis=1))

6.5
[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


In [129]:
print(test_array.std())
print(test_array.std(axis=0))
print(test_array.std(axis=1))

3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


### 6.4 수학 함수(Mathematical functions)
- 지수 함수: exp, expml, exp2, log, log10, loglp, log2, power, sqrt
- 삼각 함수: sin, cos, tan, arcsin, arccos, arctan
- Hyperbolic: sinh, cosh, tanh, arcsinh, arccosh, arctanh

In [132]:
print(np.exp(test_array))
print(np.sqrt(test_array))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


In [134]:
a = list(range(1,10))       # 이것보다 밑의 numpy로 활용하도록 하자.
import math
b = list(map(math.sqrt, a))
b

[1.0,
 1.4142135623730951,
 1.7320508075688772,
 2.0,
 2.23606797749979,
 2.449489742783178,
 2.6457513110645907,
 2.8284271247461903,
 3.0]

In [136]:
a = np.arange(1,10)
b = np.sqrt(a)

### 6.5 Concatenate(Numpy array를 합치는 함수) 

In [138]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
np.concatenate((a,b), axis=0) # 위의 결과와 동일

array([[1, 2],
       [3, 4],
       [5, 6]])

In [145]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [146]:
np.concatenate((a,b), axis=1) # 위의 결과와 동일

array([[1, 2],
       [2, 3],
       [3, 4]])

In [143]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a,b.T), axis=1) # T - Transpose

array([[1, 2, 5],
       [3, 4, 6]])

# 7. Array Operation

### 7.1 Operation btw arrays (기본적인 사칙 연산 지원)

In [149]:
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [150]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [151]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### 7.2 Dot product (Matrix 곱셈)
- (l,m) x (m,n) -> (l,n)

In [153]:
test_a = np.arange(1,7).reshape(2,3)
print(test_a)
test_b = np.arange(7,13).reshape(3,2)
print(test_b)
test_a.dot(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

### 7.3 Transpose

In [159]:
test_a = np.arange(1,7).reshape(2,3)
test_a.transpose()
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 7.4 Broadcasting (Shape이 다른 배열간 연산 지원)
- test_matrix + scalar
- test_matrix – scalar
- test_matrix * scalar
- test_matrix / scalar # 나누기
- test_matrix // scalar # 몫
- test_matrix ** 2 # 제곱


In [160]:
test_matrix = np.array([[1,2,3], [4,5,6]], float)
scalar = 3
test_matrix + scalar # Matrix – Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [169]:
# Matrix와 Vector간의 연산도 가능
test_matrix = np.arange(1,13).reshape(4,3)
print(test_matrix)

test_vector = np.arange(10,40,10)
print(test_vector)

print(test_matrix + test_vector)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]
