In [15]:
import numpy as np

# 10.1 loadtxt & savetxt 
# (Text type의 데이터를 읽고 저장하는 기능)

In [12]:
import os
os.getcwd()

'D:\\dudwlsrla92\\Python_jupyter_notebook\\2. Numpy'

In [25]:
a = np.loadtxt('TEST.txt')
print(a)

[1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9]


In [26]:
a[:10]

array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9])

In [27]:
a_int = a.astype(int)

In [28]:
a_int[:3]

array([1, 2, 3])

In [29]:
np.savetxt(filename, a_int,delimiter=‘,’) # csv 파일로 저장

SyntaxError: invalid character in identifier (<ipython-input-29-667cb25a9393>, line 1)

# 10.2 numpy object – npy